default:
  interruptible: true
  image: node:16-bullseye-slim

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"' # Run when requested manually
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run on merge request
      when: always
    - when: never # Otherwise -> Don't pipeline

stages:
  - build

build-dev:
  stage: build
  cache:
    paths:
      - frontend/.yarn/
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 day
  script:
    - npm ci
    - npm build
